### ISSUE TITLE
HTTPS connections result in exceptions

### ISSUE THREAD

**Issue by cskau** [witchard/grole#12]
To reproduce simply run grole.py and connect to https://127.0.0.1:1234/

ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<Grole._handle() done, defined at ./grole.py:336> exception=UnicodeDecodeError('utf-8', b'[Long hex string that I redacted]\n', 4, 5, 'invalid start byte')>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "./grole.py", line 349, in _handle
    await req._read(reader)
  File "./grole.py", line 45, in _read
    self.method, self.location, self.version = start_line.decode().split()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xae in position 4: invalid start byte

**Comment by witchard** [comment]
Yea, afraid it doesn’t support https currently. If i get a chance I’ll see if I can add support

**Comment by cskau** [comment]
Ah yes, I didn't mean to imply that you necessarily implement HTTPS/SSL support. Rather I meant to say that grole should probably handle it a bit more gracefully - ie. not throw an exception.
